// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-conversations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sbForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_conversations_default = defineTool({
  name: "list_conversations",
  title: "List conversations",
  description: "List the signed-in user's E'nvl\xE9 conversations, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max number of conversations (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser(ctx);
    const { data, error } = await sb.from("conversations").select("*").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-messages.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sbForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_messages_default = defineTool2({
  name: "list_messages",
  title: "List messages",
  description: "List recent messages in a conversation for the signed-in user.",
  inputSchema: {
    conversation_id: z2.string().describe("Conversation UUID."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max messages (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser2(ctx);
    const { data, error } = await sb.from("messages").select("*").eq("conversation_id", conversation_id).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/send-message.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sbForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var send_message_default = defineTool3({
  name: "send_message",
  title: "Send message",
  description: "Send a text message from the signed-in user to a conversation.",
  inputSchema: {
    conversation_id: z3.string().describe("Conversation UUID."),
    content: z3.string().min(1).describe("Message body.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ conversation_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser3(ctx);
    const { data, error } = await sb.from("messages").insert({ conversation_id, content, sender_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Message sent: ${data.id}` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sbForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool4({
  name: "get_profile",
  title: "Get my profile",
  description: "Return the signed-in user's E'nvl\xE9 profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser4(ctx);
    const { data, error } = await sb.from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sbForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_transactions_default = defineTool5({
  name: "list_transactions",
  title: "List wallet transactions",
  description: "List the signed-in user's wallet transactions, most recent first.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max transactions (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser5(ctx);
    const { data, error } = await sb.from("wallet_transactions").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ewwlsgutjoouphvopzlt";
var mcp_default = defineMcp({
  name: "envle-mcp",
  title: "E'nvl\xE9 One MCP",
  version: "0.1.0",
  instructions: "Tools for the E'nvl\xE9 One super app. Read the signed-in user's profile, conversations, messages, and wallet transactions, and send new chat messages on their behalf.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_conversations_default, list_messages_default, send_message_default, list_transactions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
